CC = g++
SOURCE = dijkstra.cpp
EXEC = Program.out 
FLAGS = -Wall -std=c++11 -o 

default: 
	$(CC) $(SOURCE) $(FLAGS) $(EXEC)

# To envoke, type make verbose
debug: 
	$(CC) -g $(SOURCE) $(FLAGS) $(EXEC)

